spring:
  application:
    name: Team49
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:team49}?useSSL=false&allowPublicKeyRetrieval=true  # ?????? ?? URL, ???? ?? MySQL
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
      jdbc:
        time_zone: Asia/Seoul
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      maxFileSize: 5MB

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

kakao:
  client_id: ${REST_API_KEY}
  redirect_uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/callback}



