spring:
  application:
    name: Team49  # ?????? ?? ??, ???? ?? ?? ? ??
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:team49}?useSSL=false&allowPublicKeyRetrieval=true  # ?????? ?? URL, ???? ?? MySQL
    username: ${DB_USERNAME:root}  # ?????? ????, ?? ??? ?? ??
    password: ${DB_PASSWORD:root}  # ?????? ????, ?? ??? ?? ??
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC ???? ????
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate? ?????? ???? ???? ?? (update? ??? ?? ? ??? ??)
      default_batch_fetch_size: 1000  # ?? ?? ? ? ?? ??? ???? ??
      jdbc:
        time_zone: Asia/Seoul  # JDBC ???? ??? ??? ??
    defer-datasource-initialization: true  # ????? ???? ???? JPA ??? ?? ???? ?? ??
    show-sql: true  # JPA? ???? SQL ??? ??? ??
    open-in-view: false  # View ????? Lazy ?? ?? (false? ???? ?? ? ?? ??)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Hibernate?? ??? MySQL ?? ??
  servlet:
    multipart:
      maxFileSize: 5MB  # ??? ??? ??? ?? ?? ??

springdoc:
  default-consumes-media-type: application/json  # REST API ???? ?? Content-Type? JSON?? ??
  default-produces-media-type: application/json  # REST API ???? ?? Content-Type? JSON?? ??

kakao:
  client_id: {REST API KEY}
  redirect_uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/callback}



