name: Deploy to EC2

on:
  push:
    branches:
      - master  # master 브랜치에 Push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # 배포 디렉토리로 이동
            cd /home/ubuntu/app
          
            # 최신 코드 가져오기
            git pull origin master
          
            # Gradle 빌드
            ./gradlew clean build -x test
          
            # 기존 애플리케이션 종료
            kill -9 $(lsof -t -i:8080) || true
          
            # 새 애플리케이션 실행
            nohup java -jar build/libs/team49-1.0.0.jar > app.log 2>&1 &
          EOF
