name: Deploy to EC2

on:
  push:
    branches:
      - feature/GOORM-6-github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          EC2_USER: ubuntu # EC2 사용자 이름
          EC2_HOST: ${{ secrets.EC2_HOST }} # EC2 호스트 주소
          EC2_PATH: 2024_DANPOONG_TEAM_49_BE # 프로젝트 경로
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REST_API_KEY: ${{ secrets.REST_API_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@${{ secrets.EC2_HOST }} << 'EOF'
          cd $EC2_PATH
          git pull origin master
          
          # application.yml 업데이트
          cat > src/main/resources/application.yml << EOL
          spring:
            datasource:
              url: jdbc:mysql://localhost:3306/${DB_NAME}
              username: ${DB_USERNAME}
              password: ${DB_PASSWORD}
          external:
            api-key: ${REST_API_KEY}
          EOL
          
          # Gradle 빌드 및 애플리케이션 실행
          ./gradlew build -x test
          nohup java -jar build/libs/*.jar > app.log 2>&1 &
          EOF
