# 워크 플로우 이름
name: Java CI with Gradle

# 워크 플로우가 언제 실행 될지를 정한다.
on:
  push:
    branches: [ "feature/GOORM-6-github-actions" ]
  pull_request:
    branches: [ "feature/GOORM-6-github-actions" ]

# 워크플로우에서 할 작업 정의한다.
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 깃허브에서 제공하는 checkout 엑션 사용
      - uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle wrapper 파일에 실행 권한을 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build -x test

      # 빌드 결과 확인
      - name: Verify Build Output
        run: ls build/libs/

      # EC2로 배포
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          echo "Private key file created and permissions set."

          # 디렉토리 생성
          echo "Ensuring target directory exists on EC2..."
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}

          # JAR 파일 업로드
          echo "Uploading JAR file to EC2 instance..."
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/team49-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/team49-0.0.1-SNAPSHOT.jar
          echo "JAR file uploaded to EC2."

          # SSH 연결 및 애플리케이션 실행
          echo "Starting SSH session on EC2..."
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

            echo "Setting environment variables on EC2..."
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export REST_API_KEY=${{ secrets.REST_API_KEY }}
            echo "Environment variables set."

            echo "Stopping existing Java processes (if any)..."
            pgrep java | xargs kill -9 || true
            echo "Existing Java processes stopped."

            echo "Starting application..."
            nohup java -jar /home/${{ secrets.EC2_USER }}/team49-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            echo "Application started."
          EOF

          # 로컬 SSH 키 삭제
          echo "Cleaning up private key..."
          rm -f private_key.pem
          echo "Private key deleted."

